//
//  단축키 정의
//
//  [단축키], [ＣＡＤ명령어]
//

a,					Arc
aa,					Area
AI_SELALL,		AI_SELALL
ar,					Array
ASNP,				ASSIGNPLAN
h,					bHatch
hatch,				bHatch
bh,					bHatch
b,					BlockDefinition
block,				BlockDefinition
bp,					BlockPrint
br,					Break
c,					Circle
ch,					Change
CEP,				CHANGEELEMPROPERTY
cha,				Chamfer
CLIPCUT,			CLIPCUT
CLIPCOPY,		CLIPCOPY 
CLIPPASTE,		CLIPPASTE
co,					Copy
cp,					Copy
col,				Color
ddcolor,			Color
ed,					DDEdit
dim1,				Dim
dal,				DimAligned
dan,				DimAngular
dbl,				DimBaseline
dco,				DimContinue
ddi,				DimDiameter
dli,					DimLinear
dra,				DimRadius
d,					DimStyle
ddim,				DimStyle
dst,				DimStyle
di,					Dist
div,				Divide
dl,					DLine
DRX,				DRAWAXIS
DRB,				DRAWBEAM
DRC,				DRAWCOL
dr,					DrawOrder
DRW,				DRAWWALL
DWGLIB,			DWGLIB
el,					Ellipse
e,					Erase
x,					Explode
EXP,				EXPORT
ex,					Extend
EB,					EXTENDBREAK
EXT,				EXTRUDE
f,					Fillet
find,				Find
FORMEDIT,		FORMEDIT
GUIDEMAP,		GUIDEMAP
ddinsert,          Insert
i,					Insert
la,					Layer
sa,					LayIso
se,					LayOff
saa,				LayOn
LO,					LAYEROFF
LL,					LAYERLEAVE
l,					Line
lm, 				Limits
lt,					LineType
lw,					LineWeight
lts,					LTScale
LI,					LIST
ma,				MatchProp
me,				Measure
mt,             MergeText
mi,					Mirror
m,					Move
MVBN,			MOVEBEAMNODE
MVCN,			MOVECOLNODE
MVWN,			MOVEWALLNODE
o,					Offset
OP,				OPTION
or,					Ortho
os,					Osnap
p,					Pan
pe,					PEdit
RD,				REDO
PBP,				PLANBP
pl,					PLine
po,					Point
PP,					Print
plot,				Print
PROPS,			PROPERTIES
pol,				PolyGon
pu,					Purge
rec,				Rectangle
r,					Redraw
re, 				Regen
rc,					RevCloud
ro,					Rotate
sc,					Scale
select,				Select
SLP,				SELPLAN
SSTR,				SELSTORY
STX,				SETAXIS
STB,				SETBEAM
STC,				SETCOL
STW,				SETWALL
SHB,				SHOWBEAM
SHBN,				SHOWBEAMNODE
SHC,				SHOWCOL
SHCN,				SHOWCOLNODE
SHW,				SHOWWALL
SHWN,			SHOWWALLNODE
SLAB,				SLAB
sn,					Snap
STAIR,				STAIR
s,					Stretch
st,					Style
SYMBOL,			SYMBOL
dtext,				Text
t,					Text
te,					TextEdit
tr,					Trim
U,					UNDO
ER,					XATTACH
w,					WriteBlock
wblock,			WriteBlock
z,					Zoom
ShowDDEditDlg,		ShowDDEditDlg